### PR TITLE
Upgrade to sprig 2.22.0

### PR DESCRIPTION
**Pull request by FUSAKLA**
Upgraded to newest v2 Sprig version 

@dohnto

### CODE REVIEW

**Comment by dohnto** [comment]
LGTM

**Comment by dohnto** [comment]
Have you run `go mod tidy`? The mod files seem quite messy.

**Comment by FUSAKLA** [comment]
Yep, this is tidy as it can be :man_shrugging:

**Review by david-vavra — APPROVED** [review]
lgtm

**Pull request merged**
