### PR TITLE
chore: use dh-golang for Debian packaging

### PR DESCRIPTION
**Pull request by mody**
Fixed Debian packaging for version `v1.1.0`

### CODE REVIEW

**Comment by dohnto** [comment]
I would suggest to merge it to branch **v1**, is that ok?

**Comment by dohnto** [comment]
I am used to build debian packages using dpkg-buildpackage, but it fails with your change:
```bash
$ dpkg-buildpackage 
dpkg-buildpackage: source package goenvtemplator
dpkg-buildpackage: source version 1.1.0
dpkg-buildpackage: source distribution Seznam
dpkg-buildpackage: source changed by Tomas Dohnalek <tomas.dohnalek@firma.seznam.cz>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build goenvtemplator
 debian/rules clean
dh clean --with=golang
   dh_testdir
   dh_auto_clean
	make -j1 clean
make[1]: Entering directory '/root/work/go/src/github.com/seznam/goenvtemplator'
rm -f goenvtemplator{,-amd64,.tar.xz}
make[1]: Leaving directory '/root/work/go/src/github.com/seznam/goenvtemplator'
   dh_clean
 dpkg-source -b goenvtemplator
dpkg-source: warning: no source format specified in debian/source/format, see dpkg-source(1)
dpkg-source: info: using source format `1.0'
dpkg-source: warning: source directory 'goenvtemplator' is not <sourcepackage>-<upstreamversion> 'goenvtemplator-1.1.0'
dpkg-source: info: building goenvtemplator in goenvtemplator_1.1.0.tar.gz
dpkg-source: info: building goenvtemplator in goenvtemplator_1.1.0.dsc
 debian/rules build
dh build --with=golang
   dh_testdir
   dh_update_autotools_config
   dh_auto_configure
   dh_auto_build
	make -j1
make[1]: Entering directory '/root/work/go/src/github.com/seznam/goenvtemplator'
go build -ldflags "-X main.buildVersion=-v1.1.0-1-gfdd9d8d"
make[1]: Leaving directory '/root/work/go/src/github.com/seznam/goenvtemplator'
   dh_auto_test
	make -j1 test
make[1]: Entering directory '/root/work/go/src/github.com/seznam/goenvtemplator'
go test
PASS
ok  	github.com/seznam/goenvtemplator	0.005s
make[1]: Leaving directory '/root/work/go/src/github.com/seznam/goenvtemplator'
 debian/rules binary
dh binary --with=golang
   dh_testroot
   dh_prep
   dh_auto_install
   dh_install
   dh_installdocs
   dh_installchangelogs
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_strip
   dh_makeshlibs
   dh_shlibdeps
   dh_installdeb
   dh_golang
Use of uninitialized value $ENV{"DH_GOPKG"} in concatenation (.) or string at /usr/share/perl5/Debian/Debhelper/Buildsystem/golang.pm line 166.
warning: "/..." matched no packages
Use of uninitialized value in split at /usr/share/perl5/Debian/Debhelper/Buildsystem/golang.pm line 168.
can't load package: package github.com/joho/godotenv: cannot find package "github.com/joho/godotenv" in any of:
	/usr/lib/go/src/github.com/joho/godotenv (from $GOROOT)
	/root/work/go/src/github.com/seznam/goenvtemplator/obj-x86_64-linux-gnu/src/github.com/joho/godotenv (from $GOPATH)
go list of dependencies failed with code 31488,  at /usr/bin/dh_golang line 58.
debian/rules:6: recipe for target 'binary' failed
make: *** [binary] Error 123
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
```

**Comment by dohnto** [comment]
In order to use your solution, I believe (according to [this](http://pkg-go.alioth.debian.org/packaging.html) we would have to debianize all go libraries we use (they all exists except `sprig`), isn't that right?

**Comment by mody** [comment]
You're right @dohnto `pbuilder` fails even for me.

**Pull request closed without merging**
